name: IanMcCall.CODES
title: IanMcCall.CODES
repository: ianmcodes/ianmcodes.github.io
url: https://www.ianmccall.codes
markdown: kramdown
highlighter: rouge
# safe: true
lsi: false
timezone: America/Chicago
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
exclude: ["bower_components", "vendor"]
defaults:
  - 
    scope: 
      path: ""
      type: "posts"
    values:
      author: "imccall"
  -
    scope:
      path: "assets"
    values:
      sitemap: false
  - 
    scope:
      path: "js"
    values:
      sitemap: false
  - 
    scope:
      path: "css"
    values:
      sitemap: false
  - 
    scope:
      path: "tronc"
    values:
      sitemap: false
  - 
    scope:
      path: "**/*_old.*"
    values:
      sitemap: false
  -
    scope:
      path: ""
    values:
      image: "/assets/images/banner.jpg"

# SEO

